<?php
header('Content-Type: application/json');

$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "filterusername") {

    $username = isset($this->viewData['username']) ? $this->viewData['username'] : '';
    $result = (new BusinessFlow())->filterusername($username);
    if($result){
        echo json_encode($result);
    }else{
        echo json_encode([['username'=>'']]);
    }

} 
if($flag == "transactiondata") {

    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result = (new BusinessFlow())->FetchTrsansactionData($page, $limit) ?? [];
    echo json_encode([
        'users' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
        'trasationIds' => $result['transactionIds']
    ]);

}

if ($flag == "getOrderid") {
    $result = (new BusinessFlow())->getOrderid();
    echo json_encode($result);
} 



